/*
 * Autogenerated by IntegraStub build system.
 * Do not edit, your changes will be lost.
 */

#pragma once
#define COLOR_EDIT EFI_TEXT_ATTR(EFI_BLACK, EFI_LIGHTGRAY)
#define COLOR_ENTRY EFI_TEXT_ATTR(EFI_LIGHTGRAY, EFI_BLACK)
#define COLOR_HIGHLIGHT EFI_TEXT_ATTR(EFI_BLACK, EFI_LIGHTGRAY)
#define COLOR_NORMAL EFI_TEXT_ATTR(EFI_LIGHTGRAY, EFI_BLACK)
#define ENABLE_TPM 1
#define HAVE_WARNING_ZERO_AS_NULL_POINTER_CONSTANT 1
#define HAVE_WARNING_ZERO_LENGTH_BOUNDS 1
#define PROJECT_URL "https://systemd.io/"
#define PROJECT_VERSION "259"
#define RELATIVE_SOURCE_PATH ".."
#define SBAT_DISTRO "EpsilonOS"
#define SBAT_DISTRO_GENERATION 1
#define SBAT_DISTRO_PKGNAME "systemd"
#define SBAT_DISTRO_SUMMARY "EpsilonOS Linux"
#define SBAT_DISTRO_URL "https://epsilonos.org/"
#define SBAT_DISTRO_VERSION GIT_VERSION
#define SBAT_PROJECT "systemd"
#define VERSION_TAG "259"